const testimonials = [
    [
        {
            id: 1,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 2,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 3,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 4,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
    ],
    [
        {
            id: 5,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 6,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 7,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 8,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
    ],
    [
        {
            id: 9,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 10,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 11,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 12,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
    ],
    [
        {
            id: 13,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 14,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 15,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
        {
            id: 16,
            name: 'Sarah Blue',
            date: '25/05/2025',
            quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit..',
            rate: 5,
            img: '/avatar.svg',
        },
    ]
]

export default testimonials;